USE [master]
go
CREATE SERVER AUDIT [SQL_Server_Audit]
TO FILE
(
FILEPATH = N'D:\SQLDATABASE\AUDIT\'
	,MAXSIZE = 102400 MB
	,MAX_ROLLOVER_FILES = 100
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)
go